import { CrearPermisoDto } from './dto/create-permiso.dto';

export const permisosSeed: CrearPermisoDto[] = [
  {
    clave: 'productos.ver',
    nombre: 'Ver productos',
    modulo: 'productos',
    descripcion: 'Permite ver el listado de productos',
  },
  {
    clave: 'productos.crear',
    nombre: 'Crear producto',
    modulo: 'productos',
    descripcion: 'Permite crear nuevos productos',
  },
  {
    clave: 'productos.editar',
    nombre: 'Editar producto',
    modulo: 'productos',
    descripcion: 'Permite editar productos existentes',
  },
  {
    clave: 'productos.eliminar',
    nombre: 'Eliminar producto',
    modulo: 'productos',
    descripcion: 'Permite eliminar productos',
  },
  {
    clave: 'stock.ver',
    nombre: 'Ver stock',
    modulo: 'stock',
    descripcion: 'Permite ver el stock disponible',
  },
  {
    clave: 'stock.editar',
    nombre: 'Editar stock',
    modulo: 'stock',
    descripcion: 'Permite modificar stock manualmente',
  },
  {
    clave: 'stock.ajuste',
    nombre: 'Ajuste de inventario',
    modulo: 'stock',
    descripcion: 'Permite hacer ajustes de inventario',
  },
  {
    clave: 'ventas.cancelar.pagada',
    nombre: 'Cancelar venta cobrada',
    modulo: 'ventas',
    descripcion: 'Permite cancelar una venta ya cobrada',
  },
  {
    clave: 'ventas.cotizacion',
    nombre: 'Crear cotización',
    modulo: 'ventas',
    descripcion: 'Permite crear cotizaciones',
  },
  {
    clave: 'ventas.cotizacion.convertir',
    nombre: 'Convertir cotización',
    modulo: 'ventas',
    descripcion: 'Permite convertir cotización en venta',
  },
  {
    clave: 'ventas.descuento.manual',
    nombre: 'Descuento manual',
    modulo: 'ventas',
    descripcion: 'Permite aplicar descuento manual sin límite',
  },
  {
    clave: 'empleados.ver',
    nombre: 'Ver empleados',
    modulo: 'empleados',
    descripcion: 'Permite ver el listado de empleados',
  },
  {
    clave: 'empleados.crear',
    nombre: 'Crear empleado',
    modulo: 'empleados',
    descripcion: 'Permite crear nuevos empleados',
  },
  {
    clave: 'empleados.editar',
    nombre: 'Editar empleado',
    modulo: 'empleados',
    descripcion: 'Permite editar datos de empleados',
  },
  {
    clave: 'empleados.desactivar',
    nombre: 'Desactivar empleado',
    modulo: 'empleados',
    descripcion: 'Permite activar o desactivar empleados',
  },
  {
    clave: 'empleados.permisos',
    nombre: 'Asignar permisos extra',
    modulo: 'empleados',
    descripcion: 'Permite asignar permisos extras a empleados',
  },
  {
    clave: 'sucursales.ver',
    nombre: 'Ver sucursales',
    modulo: 'sucursales',
    descripcion: 'Permite ver el listado de sucursales',
  },
  {
    clave: 'sucursales.crear',
    nombre: 'Crear sucursal',
    modulo: 'sucursales',
    descripcion: 'Permite crear nuevas sucursales',
  },
  {
    clave: 'sucursales.editar',
    nombre: 'Editar sucursal',
    modulo: 'sucursales',
    descripcion: 'Permite editar sucursales existentes',
  },
  {
    clave: 'caja.ver',
    nombre: 'Ver caja',
    modulo: 'caja',
    descripcion: 'Permite ver el estado de la caja',
  },
  {
    clave: 'caja.movimientos.crear',
    nombre: 'Registrar movimiento de caja',
    modulo: 'caja',
    descripcion: 'Permite registrar movimientos manuales de caja',
  },
  {
    clave: 'deposito.ver',
    nombre: 'Ver depósito',
    modulo: 'deposito',
    descripcion: 'Permite ver órdenes de despacho',
  },
  {
    clave: 'deposito.recepcionar',
    nombre: 'Recepcionar mercadería',
    modulo: 'deposito',
    descripcion: 'Permite recepcionar mercadería entrante',
  },
  {
    clave: 'reportes.ventas',
    nombre: 'Reporte de ventas',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de ventas',
  },
  {
    clave: 'reportes.caja',
    nombre: 'Reporte de caja',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de caja',
  },
  {
    clave: 'reportes.stock',
    nombre: 'Reporte de stock',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de stock',
  },
  {
    clave: 'reportes.empleados',
    nombre: 'Reporte de empleados',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de empleados',
  },
  {
    clave: 'reportes.exportar',
    nombre: 'Exportar reportes',
    modulo: 'reportes',
    descripcion: 'Permite exportar reportes',
  },
  {
    clave: 'config.medios_pago',
    nombre: 'Configurar medios de pago',
    modulo: 'config',
    descripcion: 'Permite configurar medios de pago',
  },
  {
    clave: 'config.listas_precio',
    nombre: 'Configurar listas de precio',
    modulo: 'config',
    descripcion: 'Permite configurar listas de precios',
  },
  {
    clave: 'config.roles',
    nombre: 'Gestionar roles',
    modulo: 'config',
    descripcion: 'Permite gestionar roles del sistema',
  },
  {
    clave: 'config.permisos',
    nombre: 'Gestionar permisos',
    modulo: 'config',
    descripcion: 'Permite gestionar permisos del sistema',
  },
  {
    clave: 'precios.cambiar',
    nombre: 'Cambiar lista de precios',
    modulo: 'precios',
    descripcion: 'Permite cambiar la lista de precios activa',
  },
  {
    clave: 'ventas.crear',
    nombre: 'Crear venta',
    modulo: 'ventas',
    descripcion: 'Permite crear una nueva venta',
  },
  {
    clave: 'ventas.cancelar',
    nombre: 'Cancelar venta',
    modulo: 'ventas',
    descripcion: 'Permite cancelar una venta existente',
  },
  {
    clave: 'config.pos',
    nombre: 'Configurar POS',
    modulo: 'admin',
    descripcion: 'Permite configurar el flujo del punto de venta',
  },
  {
    clave: 'config.email',
    nombre: 'Configurar email',
    modulo: 'admin',
    descripcion: 'Permite configurar credenciales y envios por correo',
  },
  {
    clave: 'reportes.ver',
    nombre: 'Ver reportes',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de ventas y caja',
  },
  {
    clave: 'caja.cerrar',
    nombre: 'Cerrar caja',
    modulo: 'caja',
    descripcion: 'Permite cerrar la caja al fin del turno',
  },
  {
    clave: 'caja.cobrar',
    nombre: 'Cobrar venta',
    modulo: 'caja',
    descripcion: 'Permite cobrar una venta',
  },
  {
    clave: 'deposito.despachar',
    nombre: 'Despachar pedido',
    modulo: 'deposito',
    descripcion: 'Permite despachar un pedido desde deposito',
  },
  {
    clave: 'caja.movimientos',
    nombre: 'Ver movimientos de caja',
    modulo: 'caja',
    descripcion: 'Permite ver los movimientos de caja',
  },
  {
    clave: 'empleados.gestionar',
    nombre: 'Gestionar empleados',
    modulo: 'admin',
    descripcion: 'Permite crear, editar y desactivar empleados',
  },
  {
    clave: 'empleados.roles',
    nombre: 'Asignar roles',
    modulo: 'admin',
    descripcion: 'Permite asignar roles a empleados',
  },
  {
    clave: 'ventas.ver',
    nombre: 'Ver ventas',
    modulo: 'ventas',
    descripcion: 'Permite ver el listado de ventas',
  },
  {
    clave: 'caja.abrir',
    nombre: 'Abrir caja',
    modulo: 'caja',
    descripcion: 'Permite abrir la caja al inicio del turno',
  },
  {
    clave: 'precios.ver',
    nombre: 'Ver lista de precios',
    modulo: 'precios',
    descripcion: 'Permite ver las listas de precios',
  },
  {
    clave: 'ventas.descuento',
    nombre: 'Aplicar descuento',
    modulo: 'ventas',
    descripcion: 'Permite aplicar descuentos en una venta',
  },
  {
    clave: 'deposito.stock',
    nombre: 'Ver stock',
    modulo: 'deposito',
    descripcion: 'Permite ver el stock disponible',
  },
];
