import { CrearPermisoDto } from './dto/create-permiso.dto';

export const permisosSeed: CrearPermisoDto[] = [
  {
    clave: 'productos.ver',
    nombre: 'Ver productos',
    modulo: 'productos',
    descripcion: 'Permite ver el listado de productos',
  },
  {
    clave: 'productos.crear',
    nombre: 'Crear producto',
    modulo: 'productos',
    descripcion: 'Permite crear nuevos productos',
  },
  {
    clave: 'productos.editar',
    nombre: 'Editar producto',
    modulo: 'productos',
    descripcion: 'Permite editar productos existentes',
  },
  {
    clave: 'productos.eliminar',
    nombre: 'Eliminar producto',
    modulo: 'productos',
    descripcion: 'Permite eliminar productos',
  },
  {
    clave: 'productos.ajustar-stock',
    nombre: 'Ajustar stock de producto',
    modulo: 'productos',
    descripcion: 'Permite modificar el stock de productos',
  },
  {
    clave: 'productos.ver_costos',
    nombre: 'Ver costos de productos',
    modulo: 'productos',
    descripcion: 'Permite ver precios de costo de productos',
  },
  {
    clave: 'productos.ver_margenes',
    nombre: 'Ver margenes de productos',
    modulo: 'productos',
    descripcion: 'Permite ver margenes de ganancia de productos',
  },
  {
    clave: 'stock.ver',
    nombre: 'Ver stock',
    modulo: 'stock',
    descripcion: 'Permite ver el stock disponible',
  },
  {
    clave: 'stock.editar',
    nombre: 'Editar stock',
    modulo: 'stock',
    descripcion: 'Permite modificar stock manualmente',
  },
  {
    clave: 'stock.ajuste',
    nombre: 'Ajuste de inventario',
    modulo: 'stock',
    descripcion: 'Permite hacer ajustes de inventario',
  },
  {
    clave: 'ventas.cancelar.pagada',
    nombre: 'Cancelar venta cobrada',
    modulo: 'ventas',
    descripcion: 'Permite cancelar una venta ya cobrada',
  },
  {
    clave: 'ventas.cotizacion',
    nombre: 'Crear cotización',
    modulo: 'ventas',
    descripcion: 'Permite crear cotizaciones',
  },
  {
    clave: 'ventas.cotizacion.convertir',
    nombre: 'Convertir cotización',
    modulo: 'ventas',
    descripcion: 'Permite convertir cotización en venta',
  },
  {
    clave: 'ventas.descuento.manual',
    nombre: 'Descuento manual',
    modulo: 'ventas',
    descripcion: 'Permite aplicar descuento manual sin límite',
  },
  {
    clave: 'empleados.ver',
    nombre: 'Ver empleados',
    modulo: 'empleados',
    descripcion: 'Permite ver el listado de empleados',
  },
  {
    clave: 'empleados.crear',
    nombre: 'Crear empleado',
    modulo: 'empleados',
    descripcion: 'Permite crear nuevos empleados',
  },
  {
    clave: 'empleados.editar',
    nombre: 'Editar empleado',
    modulo: 'empleados',
    descripcion: 'Permite editar datos de empleados',
  },
  {
    clave: 'empleados.desactivar',
    nombre: 'Desactivar empleado',
    modulo: 'empleados',
    descripcion: 'Permite activar o desactivar empleados',
  },
  {
    clave: 'empleados.permisos',
    nombre: 'Asignar permisos extra',
    modulo: 'empleados',
    descripcion: 'Permite asignar permisos extras a empleados',
  },
  {
    clave: 'sucursales.ver',
    nombre: 'Ver sucursales',
    modulo: 'sucursales',
    descripcion: 'Permite ver el listado de sucursales',
  },
  {
    clave: 'sucursales.crear',
    nombre: 'Crear sucursal',
    modulo: 'sucursales',
    descripcion: 'Permite crear nuevas sucursales',
  },
  {
    clave: 'sucursales.editar',
    nombre: 'Editar sucursal',
    modulo: 'sucursales',
    descripcion: 'Permite editar sucursales existentes',
  },
  {
    clave: 'caja.ver',
    nombre: 'Ver caja',
    modulo: 'caja',
    descripcion: 'Permite ver el estado de la caja',
  },
  {
    clave: 'caja.movimientos.crear',
    nombre: 'Registrar movimiento de caja',
    modulo: 'caja',
    descripcion: 'Permite registrar movimientos manuales de caja',
  },
  {
    clave: 'deposito.ver',
    nombre: 'Ver depósito',
    modulo: 'deposito',
    descripcion: 'Permite ver órdenes de despacho',
  },
  {
    clave: 'deposito.recepcionar',
    nombre: 'Recepcionar mercadería',
    modulo: 'deposito',
    descripcion: 'Permite recepcionar mercadería entrante',
  },
  {
    clave: 'reportes.ventas',
    nombre: 'Reporte de ventas',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de ventas',
  },
  {
    clave: 'reportes.caja',
    nombre: 'Reporte de caja',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de caja',
  },
  {
    clave: 'reportes.stock',
    nombre: 'Reporte de stock',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de stock',
  },
  {
    clave: 'reportes.empleados',
    nombre: 'Reporte de empleados',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de empleados',
  },
  {
    clave: 'reportes.exportar',
    nombre: 'Exportar reportes',
    modulo: 'reportes',
    descripcion: 'Permite exportar reportes',
  },
  {
    clave: 'config.medios_pago',
    nombre: 'Configurar medios de pago',
    modulo: 'config',
    descripcion: 'Permite configurar medios de pago',
  },
  {
    clave: 'config.listas_precio',
    nombre: 'Configurar listas de precio',
    modulo: 'config',
    descripcion: 'Permite configurar listas de precios',
  },
  {
    clave: 'config.roles',
    nombre: 'Gestionar roles',
    modulo: 'config',
    descripcion: 'Permite gestionar roles del sistema',
  },
  {
    clave: 'config.permisos',
    nombre: 'Gestionar permisos',
    modulo: 'config',
    descripcion: 'Permite gestionar permisos del sistema',
  },
  {
    clave: 'precios.cambiar',
    nombre: 'Cambiar lista de precios',
    modulo: 'precios',
    descripcion: 'Permite cambiar la lista de precios activa',
  },
  {
    clave: 'ventas.crear',
    nombre: 'Crear venta',
    modulo: 'ventas',
    descripcion: 'Permite crear una nueva venta',
  },
  {
    clave: 'ventas.cancelar',
    nombre: 'Cancelar venta',
    modulo: 'ventas',
    descripcion: 'Permite cancelar una venta existente',
  },
  {
    clave: 'admin.servicios',
    nombre: 'Configurar POS',
    modulo: 'admin',
    descripcion: 'Permite configurar el flujo del punto de venta',
  },
  {
    clave: 'admin.servicios',
    nombre: 'Configurar email',
    modulo: 'admin',
    descripcion: 'Permite configurar credenciales y envios por correo',
  },
  {
    clave: 'admin.servicios',
    nombre: 'Administrar servicios externos',
    modulo: 'admin',
    descripcion: 'Permite configurar servicios externos por sucursal',
  },
  {
    clave: 'admin.servicios',
    nombre: 'Configurar Mercado Pago',
    modulo: 'mp',
    descripcion: 'Permite guardar credenciales de Mercado Pago',
  },
  {
    clave: 'admin.leer',
    nombre: 'Ver estado de Mercado Pago',
    modulo: 'mp',
    descripcion: 'Permite probar y consultar la configuracion de Mercado Pago',
  },
  {
    clave: 'reportes.ver',
    nombre: 'Ver reportes',
    modulo: 'reportes',
    descripcion: 'Permite ver reportes de ventas y caja',
  },
  {
    clave: 'caja.cerrar',
    nombre: 'Cerrar caja',
    modulo: 'caja',
    descripcion: 'Permite cerrar la caja al fin del turno',
  },
  {
    clave: 'caja.cobrar',
    nombre: 'Cobrar venta',
    modulo: 'caja',
    descripcion: 'Permite cobrar una venta',
  },
  {
    clave: 'deposito.despachar',
    nombre: 'Despachar pedido',
    modulo: 'deposito',
    descripcion: 'Permite despachar un pedido desde deposito',
  },
  {
    clave: 'caja.movimientos',
    nombre: 'Ver movimientos de caja',
    modulo: 'caja',
    descripcion: 'Permite ver los movimientos de caja',
  },
  {
    clave: 'empleados.gestionar',
    nombre: 'Gestionar empleados',
    modulo: 'admin',
    descripcion: 'Permite crear, editar y desactivar empleados',
  },
  {
    clave: 'empleados.roles',
    nombre: 'Asignar roles',
    modulo: 'admin',
    descripcion: 'Permite asignar roles a empleados',
  },
  {
    clave: 'ventas.ver',
    nombre: 'Ver ventas',
    modulo: 'ventas',
    descripcion: 'Permite ver el listado de ventas',
  },
  {
    clave: 'caja.abrir',
    nombre: 'Abrir caja',
    modulo: 'caja',
    descripcion: 'Permite abrir la caja al inicio del turno',
  },
  {
    clave: 'precios.ver',
    nombre: 'Ver lista de precios',
    modulo: 'precios',
    descripcion: 'Permite ver las listas de precios',
  },
  {
    clave: 'ventas.descuento',
    nombre: 'Aplicar descuento',
    modulo: 'ventas',
    descripcion: 'Permite aplicar descuentos en una venta',
  },
  {
    clave: 'deposito.stock',
    nombre: 'Ver stock',
    modulo: 'deposito',
    descripcion: 'Permite ver el stock disponible',
  },
  {
    clave: 'productos.cargar',
    nombre: 'Cargar productos',
    modulo: 'productos',
    descripcion: 'Permite cargar nuevos productos desde pantallas heredadas',
  },
  {
    clave: 'productos.configurar_columnas',
    nombre: 'Configurar columnas de productos',
    modulo: 'productos',
    descripcion:
      'Permite personalizar columnas visibles en la tabla de productos',
  },
  {
    clave: 'productos.ofertas.crear',
    nombre: 'Crear ofertas de productos',
    modulo: 'productos',
    descripcion: 'Permite crear ofertas y promociones para productos',
  },
  {
    clave: 'stock.movimientos.ver',
    nombre: 'Ver movimientos de stock',
    modulo: 'stock',
    descripcion: 'Permite ver el historial de movimientos de stock',
  },
  {
    clave: 'stock.movimientos.ajustar',
    nombre: 'Ajustar movimientos de stock',
    modulo: 'stock',
    descripcion: 'Permite registrar ajustes manuales de stock',
  },
  {
    clave: 'ventas.eliminar',
    nombre: 'Eliminar ventas',
    modulo: 'ventas',
    descripcion: 'Permite eliminar o anular ventas desde pantallas heredadas',
  },
  {
    clave: 'ventas.devolver',
    nombre: 'Devolver venta',
    modulo: 'ventas',
    descripcion: 'Permite realizar devoluciones y notas de credito de ventas',
  },
  {
    clave: 'ventas.facturar',
    nombre: 'Facturar venta',
    modulo: 'ventas',
    descripcion: 'Permite emitir comprobantes fiscales o internos de una venta',
  },
  {
    clave: 'ventas.emitir_comprobante',
    nombre: 'Emitir comprobante de venta',
    modulo: 'ventas',
    descripcion: 'Permite emitir comprobantes asociados a ventas',
  },
  {
    clave: 'empleados.eliminar',
    nombre: 'Eliminar empleado',
    modulo: 'empleados',
    descripcion: 'Permite eliminar empleados del sistema',
  },
  {
    clave: 'sucursales.eliminar',
    nombre: 'Eliminar sucursal',
    modulo: 'sucursales',
    descripcion: 'Permite eliminar sucursales',
  },
  {
    clave: 'clientes.ver',
    nombre: 'Ver clientes',
    modulo: 'clientes',
    descripcion: 'Permite ver clientes y sus datos comerciales',
  },
  {
    clave: 'clientes.cargar',
    nombre: 'Cargar clientes',
    modulo: 'clientes',
    descripcion: 'Permite crear nuevos clientes',
  },
  {
    clave: 'clientes.editar',
    nombre: 'Editar clientes',
    modulo: 'clientes',
    descripcion: 'Permite modificar datos de clientes',
  },
  {
    clave: 'clientes.eliminar',
    nombre: 'Eliminar clientes',
    modulo: 'clientes',
    descripcion: 'Permite eliminar o desactivar clientes',
  },
  {
    clave: 'clientes.cuenta_corriente.ver',
    nombre: 'Ver cuenta corriente de clientes',
    modulo: 'clientes',
    descripcion: 'Permite consultar movimientos de cuenta corriente',
  },
  {
    clave: 'clientes.cuenta_corriente.operar',
    nombre: 'Operar cuenta corriente de clientes',
    modulo: 'clientes',
    descripcion:
      'Permite registrar cargos, pagos, ajustes y notas en cuenta corriente',
  },
  {
    clave: 'clientes.enviar_email',
    nombre: 'Enviar emails a clientes',
    modulo: 'clientes',
    descripcion: 'Permite enviar resumenes y comprobantes por email a clientes',
  },
  {
    clave: 'pedidos.ver',
    nombre: 'Ver pedidos',
    modulo: 'pedidos',
    descripcion: 'Permite ver pedidos y envios',
  },
  {
    clave: 'pedidos.crear',
    nombre: 'Crear pedidos',
    modulo: 'pedidos',
    descripcion: 'Permite crear pedidos con envio',
  },
  {
    clave: 'pedidos.editar',
    nombre: 'Editar pedidos',
    modulo: 'pedidos',
    descripcion: 'Permite modificar pedidos con envio',
  },
  {
    clave: 'pedidos.cambiar_estado',
    nombre: 'Cambiar estado de pedidos',
    modulo: 'pedidos',
    descripcion: 'Permite actualizar estados operativos de pedidos',
  },
  {
    clave: 'pedidos.rendir',
    nombre: 'Rendir pedidos',
    modulo: 'pedidos',
    descripcion: 'Permite registrar la rendicion de pedidos contra caja',
  },
  {
    clave: 'config.cloudinary',
    nombre: 'Configurar Cloudinary',
    modulo: 'admin',
    descripcion: 'Permite configurar el servicio de imagenes por sucursal',
  },
  {
    clave: 'auditoria.ver',
    nombre: 'Ver auditoria',
    modulo: 'auditoria',
    descripcion: 'Permite consultar historial de acciones y cambios',
  },
  {
    clave: 'precios.crear',
    nombre: 'Crear listas de precio',
    modulo: 'precios',
    descripcion: 'Permite crear listas de precio',
  },
  {
    clave: 'precios.editar',
    nombre: 'Editar listas de precio',
    modulo: 'precios',
    descripcion: 'Permite modificar listas de precio',
  },
  {
    clave: 'precios.eliminar',
    nombre: 'Eliminar listas de precio',
    modulo: 'precios',
    descripcion: 'Permite eliminar listas de precio',
  },
  {
    clave: 'roles.ver',
    nombre: 'Ver roles',
    modulo: 'seguridad',
    descripcion: 'Permite ver roles del sistema',
  },
  {
    clave: 'roles.crear',
    nombre: 'Crear roles',
    modulo: 'seguridad',
    descripcion: 'Permite crear roles del sistema',
  },
  {
    clave: 'roles.editar',
    nombre: 'Editar roles',
    modulo: 'seguridad',
    descripcion: 'Permite modificar roles del sistema',
  },
  {
    clave: 'roles.eliminar',
    nombre: 'Eliminar roles',
    modulo: 'seguridad',
    descripcion: 'Permite eliminar roles del sistema',
  },
  {
    clave: 'permisos.ver',
    nombre: 'Ver permisos',
    modulo: 'seguridad',
    descripcion: 'Permite ver permisos del sistema',
  },
  {
    clave: 'permisos.crear',
    nombre: 'Crear permisos',
    modulo: 'seguridad',
    descripcion: 'Permite crear permisos del sistema',
  },
  {
    clave: 'permisos.editar',
    nombre: 'Editar permisos',
    modulo: 'seguridad',
    descripcion: 'Permite modificar permisos del sistema',
  },
  {
    clave: 'permisos.eliminar',
    nombre: 'Eliminar permisos',
    modulo: 'seguridad',
    descripcion: 'Permite eliminar permisos del sistema',
  },
  {
    clave: 'categorias.ver',
    nombre: 'Ver categorias de productos',
    modulo: 'productos',
    descripcion: 'Permite ver categorias de productos',
  },
  {
    clave: 'categorias.crear',
    nombre: 'Crear categorias de productos',
    modulo: 'productos',
    descripcion: 'Permite crear categorias de productos',
  },
  {
    clave: 'categorias.editar',
    nombre: 'Editar categorias de productos',
    modulo: 'productos',
    descripcion: 'Permite modificar categorias de productos',
  },
  {
    clave: 'categorias.eliminar',
    nombre: 'Eliminar categorias de productos',
    modulo: 'productos',
    descripcion: 'Permite eliminar categorias de productos',
  },
  {
    clave: 'marcas.ver',
    nombre: 'Ver marcas de productos',
    modulo: 'productos',
    descripcion: 'Permite ver marcas de productos',
  },
  {
    clave: 'marcas.crear',
    nombre: 'Crear marcas de productos',
    modulo: 'productos',
    descripcion: 'Permite crear marcas de productos',
  },
  {
    clave: 'marcas.editar',
    nombre: 'Editar marcas de productos',
    modulo: 'productos',
    descripcion: 'Permite modificar marcas de productos',
  },
  {
    clave: 'marcas.eliminar',
    nombre: 'Eliminar marcas de productos',
    modulo: 'productos',
    descripcion: 'Permite eliminar marcas de productos',
  },
  {
    clave: 'imagenes.ver',
    nombre: 'Ver imagenes',
    modulo: 'productos',
    descripcion: 'Permite ver imagenes de productos',
  },
  {
    clave: 'imagenes.subir',
    nombre: 'Subir imagenes',
    modulo: 'productos',
    descripcion: 'Permite subir imagenes de productos',
  },
  {
    clave: 'imagenes.editar',
    nombre: 'Editar imagenes',
    modulo: 'productos',
    descripcion: 'Permite modificar orden, rol o datos de imagenes',
  },
  {
    clave: 'imagenes.eliminar',
    nombre: 'Eliminar imagenes',
    modulo: 'productos',
    descripcion: 'Permite eliminar imagenes de productos',
  },
  {
    clave: 'ofertas.ver',
    nombre: 'Ver ofertas',
    modulo: 'productos',
    descripcion: 'Permite ver ofertas de productos',
  },
  {
    clave: 'ofertas.crear',
    nombre: 'Crear ofertas',
    modulo: 'productos',
    descripcion: 'Permite crear ofertas de productos',
  },
  {
    clave: 'ofertas.editar',
    nombre: 'Editar ofertas',
    modulo: 'productos',
    descripcion: 'Permite modificar ofertas de productos',
  },
  {
    clave: 'ofertas.eliminar',
    nombre: 'Eliminar ofertas',
    modulo: 'productos',
    descripcion: 'Permite eliminar ofertas de productos',
  },
  {
    clave: 'lotes.ver',
    nombre: 'Ver lotes',
    modulo: 'productos',
    descripcion: 'Permite ver lotes de productos',
  },
  {
    clave: 'lotes.crear',
    nombre: 'Crear lotes',
    modulo: 'productos',
    descripcion: 'Permite crear lotes de productos',
  },
  {
    clave: 'lotes.editar',
    nombre: 'Editar lotes',
    modulo: 'productos',
    descripcion: 'Permite modificar lotes de productos',
  },
  {
    clave: 'lotes.eliminar',
    nombre: 'Eliminar lotes',
    modulo: 'productos',
    descripcion: 'Permite eliminar lotes de productos',
  },
  {
    clave: 'variantes.ver',
    nombre: 'Ver variantes',
    modulo: 'productos',
    descripcion: 'Permite ver variantes de productos',
  },
  {
    clave: 'variantes.crear',
    nombre: 'Crear variantes',
    modulo: 'productos',
    descripcion: 'Permite crear variantes de productos',
  },
  {
    clave: 'variantes.editar',
    nombre: 'Editar variantes',
    modulo: 'productos',
    descripcion: 'Permite modificar variantes de productos',
  },
  {
    clave: 'variantes.eliminar',
    nombre: 'Eliminar variantes',
    modulo: 'productos',
    descripcion: 'Permite eliminar variantes de productos',
  },
  {
    clave: 'comprobantes.ver',
    nombre: 'Ver comprobantes',
    modulo: 'comprobantes',
    descripcion: 'Permite ver comprobantes',
  },
  {
    clave: 'comprobantes.crear',
    nombre: 'Crear comprobantes',
    modulo: 'comprobantes',
    descripcion: 'Permite crear comprobantes',
  },
  {
    clave: 'comprobantes.editar',
    nombre: 'Editar comprobantes',
    modulo: 'comprobantes',
    descripcion: 'Permite modificar comprobantes',
  },
  {
    clave: 'comprobantes.cambiar_estado',
    nombre: 'Cambiar estado de comprobantes',
    modulo: 'comprobantes',
    descripcion: 'Permite cambiar el estado de comprobantes',
  },
  {
    clave: 'comprobantes.enviar_email',
    nombre: 'Enviar comprobantes por email',
    modulo: 'comprobantes',
    descripcion: 'Permite enviar comprobantes por email',
  },
  {
    clave: 'comprobantes.numeradores',
    nombre: 'Ver numeradores de comprobantes',
    modulo: 'comprobantes',
    descripcion: 'Permite consultar numeradores de comprobantes',
  },
  {
    clave: 'facturacion.ver',
    nombre: 'Ver facturacion',
    modulo: 'facturacion',
    descripcion: 'Permite consultar comprobantes fiscales emitidos',
  },
  {
    clave: 'facturacion.emitir',
    nombre: 'Emitir facturacion',
    modulo: 'facturacion',
    descripcion: 'Permite emitir comprobantes fiscales',
  },
  {
    clave: 'facturacion.anular',
    nombre: 'Anular facturacion',
    modulo: 'facturacion',
    descripcion: 'Permite anular comprobantes fiscales',
  },
  {
    clave: 'medios_pago.ver',
    nombre: 'Ver medios de pago',
    modulo: 'config',
    descripcion: 'Permite ver medios de pago',
  },
  {
    clave: 'medios_pago.crear',
    nombre: 'Crear medios de pago',
    modulo: 'config',
    descripcion: 'Permite crear medios de pago',
  },
  {
    clave: 'medios_pago.editar',
    nombre: 'Editar medios de pago',
    modulo: 'config',
    descripcion: 'Permite modificar medios de pago',
  },
  {
    clave: 'medios_pago.eliminar',
    nombre: 'Eliminar medios de pago',
    modulo: 'config',
    descripcion: 'Permite eliminar medios de pago',
  },
];
