export type RoleSeed = {
  nombre: string;
  descripcion: string;
  rutaInicio: string;
  permisosClaves: string[];
};

export const rolesSeed: RoleSeed[] = [
  {
    nombre: 'Vendedor',
    descripcion: 'Puede crear y gestionar ventas',
    rutaInicio: '/pos/ventas',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.ver',
      'ventas.descuento',
      'precios.ver',
      'productos.ver',
      'stock.ver',
    ],
  },
  {
    nombre: 'Cajero',
    descripcion: 'Puede cobrar ventas y manejar caja',
    rutaInicio: '/pos/caja',
    permisosClaves: [
      'ventas.ver',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'productos.ver',
      'stock.ver',
    ],
  },
  {
    nombre: 'Vendedor Cajero',
    descripcion: 'Puede vender y cobrar',
    rutaInicio: '/pos/ventas',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.ver',
      'ventas.descuento',
      'precios.ver',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'productos.ver',
      'stock.ver',
    ],
  },
  {
    nombre: 'Despacho',
    descripcion: 'Puede ver stock y despachar pedidos',
    rutaInicio: '/despachos',
    permisosClaves: [
      'deposito.ver',
      'deposito.despachar',
      'deposito.stock',
      'productos.ver',
      'stock.ver',
      'ventas.ver',
    ],
  },
  {
    nombre: 'Gerente',
    descripcion: 'Acceso completo excepto configuracion del sistema',
    rutaInicio: '/pos/reportes',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.ver',
      'ventas.descuento',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'precios.ver',
      'precios.cambiar',
      'deposito.despachar',
      'deposito.stock',
      'productos.ver',
      'stock.ver',
      'empleados.gestionar',
      'empleados.roles',
      'reportes.ver',
    ],
  },
  {
    nombre: 'Admin',
    descripcion: 'Acceso total al sistema',
    rutaInicio: '/admin',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.ver',
      'ventas.descuento',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'precios.ver',
      'precios.cambiar',
      'deposito.despachar',
      'deposito.stock',
      'empleados.gestionar',
      'empleados.roles',
      'reportes.ver',
      'config.pos',
      'config.email',
    ],
  },
];
