export type RoleSeed = {
  nombre: string;
  descripcion: string;
  rutaInicio: string;
  permisosClaves: string[];
};

export const rolesSeed: RoleSeed[] = [
  {
    nombre: 'Vendedor',
    descripcion: 'Puede crear y gestionar ventas',
    rutaInicio: '/punto-venta',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.ver',
      'ventas.descuento',
      'precios.ver',
      'productos.ver',
      'clientes.ver',
      'clientes.cargar',
      'stock.ver',
    ],
  },
  {
    nombre: 'Cajero',
    descripcion: 'Puede cobrar ventas y manejar caja',
    rutaInicio: '/caja',
    permisosClaves: [
      'ventas.ver',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'productos.ver',
      'clientes.ver',
      'stock.ver',
    ],
  },
  {
    nombre: 'Vendedor Cajero',
    descripcion: 'Puede vender y cobrar',
    rutaInicio: '/punto-venta',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.ver',
      'ventas.descuento',
      'precios.ver',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'productos.ver',
      'clientes.ver',
      'clientes.cargar',
      'stock.ver',
    ],
  },
  {
    nombre: 'Despacho',
    descripcion: 'Puede ver stock y despachar pedidos',
    rutaInicio: '/despachos',
    permisosClaves: [
      'deposito.ver',
      'deposito.despachar',
      'deposito.stock',
      'pedidos.ver',
      'pedidos.cambiar_estado',
      'productos.ver',
      'stock.ver',
      'ventas.ver',
    ],
  },
  {
    nombre: 'Gerente',
    descripcion: 'Acceso completo excepto configuracion del sistema',
    rutaInicio: '/reportes-pos',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.ver',
      'ventas.descuento',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'precios.ver',
      'precios.cambiar',
      'precios.crear',
      'precios.editar',
      'precios.eliminar',
      'deposito.despachar',
      'deposito.stock',
      'pedidos.ver',
      'pedidos.crear',
      'pedidos.editar',
      'pedidos.cambiar_estado',
      'pedidos.rendir',
      'productos.ver',
      'productos.crear',
      'productos.cargar',
      'productos.editar',
      'productos.configurar_columnas',
      'productos.ofertas.crear',
      'productos.ajustar-stock',
      'productos.ver_costos',
      'productos.ver_margenes',
      'stock.ver',
      'stock.editar',
      'stock.ajuste',
      'stock.movimientos.ver',
      'stock.movimientos.ajustar',
      'clientes.ver',
      'clientes.cargar',
      'clientes.editar',
      'clientes.cuenta_corriente.ver',
      'clientes.cuenta_corriente.operar',
      'clientes.enviar_email',
      'comprobantes.ver',
      'comprobantes.crear',
      'comprobantes.editar',
      'comprobantes.cambiar_estado',
      'comprobantes.enviar_email',
      'comprobantes.numeradores',
      'facturacion.ver',
      'facturacion.emitir',
      'facturacion.anular',
      'categorias.ver',
      'categorias.crear',
      'categorias.editar',
      'marcas.ver',
      'marcas.crear',
      'marcas.editar',
      'imagenes.ver',
      'imagenes.subir',
      'imagenes.editar',
      'ofertas.ver',
      'ofertas.crear',
      'ofertas.editar',
      'lotes.ver',
      'lotes.crear',
      'lotes.editar',
      'variantes.ver',
      'variantes.crear',
      'variantes.editar',
      'empleados.gestionar',
      'empleados.roles',
      'reportes.ver',
      'reportes.ventas',
      'reportes.caja',
      'reportes.stock',
      'reportes.empleados',
      'reportes.exportar',
      'auditoria.ver',
    ],
  },
  {
    nombre: 'Admin',
    descripcion: 'Acceso total al sistema',
    rutaInicio: '/ajustes',
    permisosClaves: [
      'ventas.crear',
      'ventas.cancelar',
      'ventas.cancelar.pagada',
      'ventas.ver',
      'ventas.descuento',
      'ventas.descuento.manual',
      'ventas.cotizacion',
      'ventas.cotizacion.convertir',
      'ventas.eliminar',
      'ventas.devolver',
      'ventas.facturar',
      'ventas.emitir_comprobante',
      'caja.cobrar',
      'caja.abrir',
      'caja.cerrar',
      'caja.ver',
      'caja.movimientos',
      'caja.movimientos.crear',
      'precios.ver',
      'precios.cambiar',
      'precios.crear',
      'precios.editar',
      'precios.eliminar',
      'deposito.despachar',
      'deposito.recepcionar',
      'deposito.ver',
      'deposito.stock',
      'pedidos.ver',
      'pedidos.crear',
      'pedidos.editar',
      'pedidos.cambiar_estado',
      'pedidos.rendir',
      'empleados.gestionar',
      'empleados.ver',
      'empleados.crear',
      'empleados.editar',
      'empleados.desactivar',
      'empleados.eliminar',
      'empleados.permisos',
      'empleados.roles',
      'reportes.ver',
      'reportes.ventas',
      'reportes.caja',
      'reportes.stock',
      'reportes.empleados',
      'reportes.exportar',
      'productos.ver',
      'productos.crear',
      'productos.cargar',
      'productos.editar',
      'productos.eliminar',
      'productos.ajustar-stock',
      'productos.configurar_columnas',
      'productos.ofertas.crear',
      'productos.ver_costos',
      'productos.ver_margenes',
      'stock.ver',
      'stock.editar',
      'stock.ajuste',
      'stock.movimientos.ver',
      'stock.movimientos.ajustar',
      'sucursales.ver',
      'sucursales.crear',
      'sucursales.editar',
      'sucursales.eliminar',
      'clientes.ver',
      'clientes.cargar',
      'clientes.editar',
      'clientes.eliminar',
      'clientes.cuenta_corriente.ver',
      'clientes.cuenta_corriente.operar',
      'clientes.enviar_email',
      'config.pos',
      'config.email',
      'config.cloudinary',
      'config.medios_pago',
      'config.listas_precio',
      'config.roles',
      'config.permisos',
      'admin.servicios',
      'mp.crear',
      'mp.leer',
      'auditoria.ver',
      'roles.ver',
      'roles.crear',
      'roles.editar',
      'roles.eliminar',
      'permisos.ver',
      'permisos.crear',
      'permisos.editar',
      'permisos.eliminar',
      'categorias.ver',
      'categorias.crear',
      'categorias.editar',
      'categorias.eliminar',
      'marcas.ver',
      'marcas.crear',
      'marcas.editar',
      'marcas.eliminar',
      'imagenes.ver',
      'imagenes.subir',
      'imagenes.editar',
      'imagenes.eliminar',
      'ofertas.ver',
      'ofertas.crear',
      'ofertas.editar',
      'ofertas.eliminar',
      'lotes.ver',
      'lotes.crear',
      'lotes.editar',
      'lotes.eliminar',
      'variantes.ver',
      'variantes.crear',
      'variantes.editar',
      'variantes.eliminar',
      'comprobantes.ver',
      'comprobantes.crear',
      'comprobantes.editar',
      'comprobantes.cambiar_estado',
      'comprobantes.enviar_email',
      'comprobantes.numeradores',
      'facturacion.ver',
      'facturacion.emitir',
      'facturacion.anular',
      'medios_pago.ver',
      'medios_pago.crear',
      'medios_pago.editar',
      'medios_pago.eliminar',
    ],
  },
];
