export enum EstadoVenta {
  COTIZACION = 'COTIZACION',
  ABIERTA = 'ABIERTA',
  PENDIENTE_PAGO = 'PENDIENTE_PAGO',
  PAGADA = 'PAGADA',
  PENDIENTE_DESPACHO = 'PENDIENTE_DESPACHO',
  DESPACHADA = 'DESPACHADA',
  CANCELADA = 'CANCELADA',
  VENCIDA = 'VENCIDA',
}
